const ids = {
    METABASE_DATABASE: 26,
    //SHMTAB01
    METABASE_TABLE_UNIDADE: 1038,
    //SHMDES01
    METABASE_TABLE_DESIGNACAO: 1133,
    //SHMCAD01
    METABASE_TABLE_MAGISTRADO: 1217,
    //SHMDES21
    METABASE_TABLE_TIPO_DESIGNACAO: 833,
    //SHMDES22
    METABASE_TABLE_MOTIVO_DESIGNACAO: 1143,
    //SMHTAB02
    METABASE_TABLE_CRITERIO_PROMOCAO: 1235,
    //SHMTAB03
    METABASE_TABLE_CARGO_PROMOCAO: 907,
    //SHMPRO01
    METABASE_TABLE_PROMOCAO: 894,
    //SHMCAD10
    METABASE_TABLE_REMOCAO: 1175,
    //SMHREM2
    METABASE_TABLE_MOTIVO_REMOCAO: 1069,

    METABASE_TABLE_FERIAS: 1008,

    METABASE_TABLE_AUSENCIAS: 1368,
}

export default ids